### ISSUE TITLE
About 'lidar_aug_matrix' in get_loss()

### ISSUE THREAD

**Issue by Ryze0124** [jbwang1997/StabilityIndex#2]
Why need transform bboxes(targets and preds), when you get 'si_reg_loss' and 'si_cls_loss'? 
Please tell me, THX!!!

**Comment by Ryze0124** [comment]
down!  got it ,read paper again. thx

**Comment by jbwang1997** [comment]
Hello. Thanks for your interests. This is because that we need to align the coordinate system between the two frames to the one before data augmentation.
